# Sử dụng một image Node.js chính thức làm base image
FROM node:18-alpine

# Tạo và chỉ định thư mục làm việc trong container
WORKDIR /app

# Sao chép package.json và package-lock.json vào thư mục làm việc
COPY package*.json ./

# Cài đặt các dependencies của dự án
RUN npm install

# Sao chép toàn bộ mã nguồn của backend vào container
COPY . .

# Expose cổng mà ứng dụng Node.js của bạn đang chạy
# Thay 5000 bằng cổng của bạn nếu khác
EXPOSE 80

# Lệnh để khởi chạy ứng dụng khi container bắt đầu
CMD [ "npm", "start" ]