name: Deploy to Windows Server

# Kích hoạt workflow này mỗi khi có code được đẩy lên nhánh `main`
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    # Chạy job này trên runner bạn vừa cài trên server
    runs-on: self-hosted

    steps:
      # Bước 1: Lấy mã nguồn mới nhất từ GitHub về server
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20' # <-- SỬA LẠI PHIÊN BẢN NODE.JS
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      # Bước 3: Build dự án Frontend
      - name: Build Frontend
        run: |
          cd client
          npm install
          npm run build
      
      # Bước 4 (QUAN TRỌNG): Sao chép Frontend đã build đến thư mục của IIS
      - name: Copy Frontend to IIS Directory
        shell: pwsh # Chỉ định dùng PowerShell
        run: |
          robocopy client\dist "C:\Users\Administrator\Documents\application-management\client\dist" /E /PURGE
          if ($LASTEXITCODE -lt 8) { exit 0 } else { exit $LASTEXITCODE }

      # Bước 5: Deploy Backend
      - name: Deploy server
        run: |
          robocopy backend "C:\Users\Administrator\Documents\application-management\server" /E /PURGE

          # Cài đặt và reload
          cd server
          npm install
          pm2 reload app-manager-api --update-env 